language: php

before_install:
  - git submodule update --init
  - composer install

php:
  - "nightly"
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

branches:
  only:
    - master
    - develop

script: php test.php

matrix:
  allow_failures:
  - php: "nightly"

